[project]
name = "ahc048"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ac-library-python>=0.1.0",
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "optuna>=4.2.1",
    "pillow>=11.1.0",
    "plotly>=6.0.1",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.2",
    "sympy>=1.14.0",
]
